version: '3.8'

volumes:
  db:
    driver: local
  pgadmin:
    driver: local


services:
  fast-api-benchmark:
    volumes:
      - ..:/workspace
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: fast-api-benchmark-container

  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - PGHOST=${POSTGRES_HOST:-localhost}
      - PGPORT=${POSTGRES_PORT:-5432}
      - PGDATABASE=${POSTGRES_DB_NAME:-fast_api_service_db}
      - PGUSER=${POSTGRES_USER:-user}
      - PGPASSWORD=${POSTGRES_PASSWORD:-pass}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    environment:
     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-example@mail.com}
     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-pass}
     - PGADMIN_LISTEN_PORT=${PGADMIN_PORT:-5050}
    ports:
      - '5050:5050'
    volumes:
      - pgadmin:/var/lib/pgadmin
