version: '3.8'

volumes:
  db:
    driver: local
  pgadmin:
    driver: local


services:
  fast-api-benchmark:
    volumes:
      - ..:/workspace
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: fast-api-benchmark-container

  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_DB=${POSTGRES_DB_NAME:-fast_api_service_db}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  test-db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
      - POSTGRES_DB=fast_api_service_test_db
    ports:
      - '5433:5432'

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    environment:
     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-example@mail.com}
     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-pass}
     - PGADMIN_LISTEN_PORT=${PGADMIN_PORT:-5050}
    ports:
      - '5050:5050'
    volumes:
      - pgadmin:/var/lib/pgadmin
