name: basic

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt

    - name: Check typing with mypy
      run: mypy ./src/

    - name: Format with Black
      run: black ./src/

    - name: Lint with flake8
      run: flake8 ./src/

    - name: Test with PyTest
      run: python3 -m pytest ./src/tests/
