name: checks

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest

    services:
      # service that will set up test db
      test-db:
        image: postgres:15.2-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: fast_api_service_test_db

        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Create env file from test env
      run: mv ./.env.test ./.env

    - name: Move Dockerfile from devcontainer
      run: mv ./.devcontainer/Dockerfile ./Dockerfile

    - name: Set docker image from devcontainer
      uses: ./.github/

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt

    - name: Check typing with mypy
      run: mypy ./src/

    - name: Format with Black
      run: black ./src/

    - name: Lint with flake8
      run: flake8 ./src/

    - name: Test with PyTest
      run: python3 -m pytest ./src/tests/
